import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { Breadcrumb } from "@/components/dashboard/page-header";
import { ResourceIcon } from "@/components/dashboard/resource-icon";
import { TabNav, type TabDef } from "@/components/dashboard/tab-nav";
import { getAgentsUsingResource } from "@/lib/data/agents";
import {
  CATALOG_LABEL,
  catalogCountLabel,
  RESOURCE_KIND_LABEL,
  RESOURCES,
  getResource,
} from "@/lib/data/resources";

export function generateStaticParams() {
  return RESOURCES.map((resource) => ({ resourceId: resource.id }));
}

export async function generateMetadata({
  params,
}: {
  params: Promise<{ resourceId: string }>;
}): Promise<Metadata> {
  const { resourceId } = await params;
  return { title: getResource(resourceId)?.name ?? "Resource" };
}

// `LayoutProps` is generated by `next typegen` and keyed on the literal route,
// so params stay in sync with the folder name automatically.
export default async function ResourceDetailLayout({
  params,
  children,
}: LayoutProps<"/resources/[resourceId]">) {
  const { resourceId } = await params;
  const resource = getResource(resourceId);
  if (!resource) notFound();

  const agents = getAgentsUsingResource(resource.id);
  const agentCount = `${agents.length} agent${agents.length === 1 ? "" : "s"}`;

  // The catalog tab is named after what the resource actually exposes. "Permissions"
  // is deliberately absent from this page: what a resource offers is global, but a
  // permission is something one agent holds, and lives on that agent.
  const tabs: readonly TabDef[] = [
    { segment: "", label: "Information" },
    { segment: "capabilities", label: CATALOG_LABEL[resource.kind] },
    { segment: "agents", label: "Agents" },
    { segment: "policies", label: "Default policies" },
    { segment: "settings", label: "Settings" },
  ];

  return (
    <>
      <Breadcrumb items={[{ label: "Resources", href: "/resources" }, { label: resource.name }]} />

      <div className="mb-6">
        <div className="flex items-center gap-2.5">
          <ResourceIcon id={resource.id} kind={resource.kind} className="size-5 text-muted" />
          <h1 className="font-mono text-[22px] font-semibold">{resource.name}</h1>
        </div>
        <p className="mt-1 text-[13.5px] text-muted">
          {RESOURCE_KIND_LABEL[resource.kind]} · {catalogCountLabel(resource)} · used by{" "}
          {agentCount}
        </p>
      </div>

      <TabNav
        basePath={`/resources/${resource.id}`}
        tabs={tabs}
        label={`${resource.name} sections`}
      />

      {children}
    </>
  );
}
