export type MarketplaceListing = {
  slug: string;
  name: string;
  provider: string;
  description: string;
  defaultMCPName: string;
  defaultNamespace: string;
  transportOptions: Array<{
    id: string;
    label: string;
    description?: string;
    transport: string;
    recommended: boolean;
    command?: string;
    args?: string[];
    url?: string;
    headers?: Record<string, string>;
    env?: Record<string, string>;
    fields: Array<{
      name: string;
      label: string;
      description?: string;
      placeholder?: string;
      required: boolean;
      secret: boolean;
      target: string;
      key?: string;
      template?: string;
    }>;
  }>;
};

export type Overview = {
  workspace: { id: number; name: string };
  agents: Array<{
    id: string;
    workspaceId: string;
    name: string;
    owner: string;
    tags: string[];
    status: string;
    createdAt: string;
    lastSeenAt?: string;
  }>;
  mcps: Array<{
    id: string;
    workspaceId: string;
    agentId?: string;
    name: string;
    namespace: string;
    transport: string;
    endpoint?: string;
    credentialRef?: string;
    command?: string;
    args?: string[];
    url?: string;
    method?: string;
    urlTemplate?: string;
    credentialTarget?: string;
    credentialName?: string;
    inputSchema?: Record<string, unknown>;
    outputSchema?: Record<string, unknown>;
    headers?: Record<string, string>;
    env?: Record<string, string>;
    enabled: boolean;
    secretEnvKeys?: string[];
    secretHeaderKeys?: string[];
    status: string;
    lastError?: string;
    tools?: Array<{ name: string }>;
    createdAt: string;
  }>;
  policies: Array<{
    id: string;
    workspaceId: string;
    name: string;
    subjectType: string;
    subjectValue: string;
    tool: string;
    actionName: string;
    effect: string;
    condition?: { field?: string; operator?: string; value?: string | number | boolean };
    rateLimit?: string;
    channelOverride?: string;
    precedence: number;
    createdAt: string;
  }>;
  auditLogs: Array<{
    id: string;
    agentId?: string;
    toolId?: string;
    tool: string;
    action?: string;
    decision: string;
    decidedBy?: string;
    latencyMs?: number;
    createdAt: string;
    payloadSummary?: Record<string, unknown>;
    request?: Record<string, unknown>;
    response?: Record<string, unknown>;
  }>;
  approvalIntegrations: Array<{
    id: string;
    workspaceId: string;
    provider: string;
    status: string;
    defaultChannel?: string;
    credentialRef?: string;
    createdAt: string;
    updatedAt: string;
  }>;
};
